Portfolio/Portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from dashboard.views import home_view

urlpatterns = [
    path('portfolio/',include('dashboard.urls', namespace='portfolio')),
    path('',home_view,name='home'),
    path('admin/', admin.site.urls),
    ]

Portfolio/dashboard/urls.py
from django.urls import path

from dashboard.views import (stock_create_view,
    portfolio_view,
    stock_list_view,
    
    single_stock_details,
    )      #render_initial_data, list_view_with_avg_bp, 
    #stock_detail_view, dynamic_lookup_view,


app_name = 'dashboard'
urlpatterns = [
    # path('stock/',stock_detail_view),    
    path('create/', stock_create_view, name='stock_create_view'),
    path('',portfolio_view, name='portfolio'),
    # path('',list_view_with_avg_bp, name='portfolio'),
    path('stocks/',stock_list_view, name='stock_list_view'),
    # path('stocks/<int:my_id>/',dynamic_lookup_view, name='stock'),
    path('stocks/<slug:my_name>/',single_stock_details, name='stock'),

    # path('initial/',render_initial_data),
]

Portfolio/dashboard/models.py
from django.db import models
from django.urls import reverse
from django.db.models import FloatField
from django.db.models.functions import Cast
from django.template.defaultfilters import slugify

# Create your models here.

class Stock(models.Model):
    name = models.TextField(blank=False, null=False)
    quantity = models.IntegerField()
    buy_price = models.DecimalField(decimal_places=2, max_digits=10000)
    buy_date = models.DateField()
    updated = models.DateField(auto_now_add=True)
    slug = models.SlugField(null=True, blank=True)
    DisplayFields = ['name', 'quantity', 'buy_price', 'total', 'buy_date', 'updated']
    SearchableFields = ['name']

    class Meta:
        db_table = 'STOCKS'

    @property
    def total(self):
        total = self.quantity * self.buy_price
        return total
        

    def sum_of_total(self):
        total = 0
        for i in self.name.all():
            total += i.qty_price_mul()
        return total

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # return reverse("portfolio:stock", kwargs={"my_name":self.slug})
        return reverse("portfolio:stock", kwargs={"my_name":self.slug})


class Gold(models.Model):
    grams = models.DecimalField(decimal_places=2, max_digits=10000)
    buy_price = models.DecimalField(decimal_places=2, max_digits=10000)

Portfolio/dashboard/forms.py
from logging import PlaceHolder
from django import forms

from .models import Stock

class StockAddForm(forms.ModelForm):

    name = forms.CharField(label="Name", widget=forms.TextInput(attrs={"placeholder":"Enter company/stock name",
                                                                        "class":"form-control",
                                                                        "list":"datalistOptions",
                                                                        "id":"exampleDataList colFormLabel"
                                                                        }))

    quantity = forms.IntegerField(widget=forms.TextInput(attrs={"placeholder":"ex: 12", "class":"form-control", "id":"colFormLabel"}))

    buy_price = forms.DecimalField(decimal_places=2, max_digits=10000, widget=forms.TextInput(attrs={"placeholder":"ex: 625.85", "class":"form-control", "id":"colFormLabel"}))

    buy_date = forms.DateField(widget=forms.DateInput(format='%d-%m-%Y', attrs={"placeholder":"ex: 25-02-2018", "class":"form-control", "id":"colFormLabel"}),
                                                    input_formats=['%d-%m-%Y'])

    class Meta:
        model = Stock
        fields = [
            'name',
            'quantity',
            'buy_price',
            'buy_date',
        ]

Portfolio/dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Sum

from .models import Stock, Gold
from .forms import StockAddForm

from pandas import Series, DataFrame
import pandas as pd
from nsetools import Nse

# Create your views here.


def home_view(request):
    # print(args,kwargs)
    # print(request.user)
    # return HttpResponse("<h1>Hello World</h1>")
    return render(request,"base.html",{})




def stock_create_view(request):
    form = StockAddForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = StockAddForm()

    stocks_dictionary = Nse().get_stock_codes()
    stock_names_list = list(Nse().get_stock_codes().values())
    
    
    context = {
        'form' : form,
        'stock_names_list' : stock_names_list,
        'stocks_dictionary' : stocks_dictionary
    }

    return render(request,"stocks/stock_create.html",context)


def portfolio_view(request):
    # stockset = Stock.objects.all()
    gold = Gold.objects.all()
    # value1 = Stock.objects.all().aggregate(new=(Sum('buy_price')))
    # value2 = Stock.objects.all().aggregate(new=(Sum('qty_price_mul()')))
    # new_value = Stock
    # list_of = new_value.qty_price_mul(stockset)
    # print(list_of)
    total = 0
    for i in Stock.objects.all():
        total += (i.buy_price*i.quantity)
            
    context = {
        "gold_list":gold,
        "equity_sum":total,
    }
    return render(request,"stocks/portfolio.html",context)


def stock_list_view(request):
    stockset = Stock.objects.all()

    name = []
    qty = []
    bp = []
    ttl = []
    for i in Stock.objects.all():
        name.append(i.name)
        qty.append(i.quantity)
        bp.append(i.buy_price)
        ttl.append(i.buy_price*i.quantity)

    data = {
        'name':name,
        'qty':qty,
        'bp':bp,
        'ttl':ttl
    }
    df = pd.DataFrame(data=data)

    sum_of_qty = df.groupby('name')['qty'].sum()
    sum_bp = df.groupby('name')['ttl'].sum()

    avg_bp = sum_bp/sum_of_qty

    set_name = set(name)

    new_dict = {}

    for i in set_name:
        new_dict[i] = sum_of_qty[i],avg_bp[i]

    fname = []
    fqty = []
    fbp = []
    fttl = []
    for i in set_name:
        fname.append(i)
        fqty.append(sum_of_qty[i])
        fbp.append(avg_bp[i])
        fttl.append(sum_of_qty[i]*avg_bp[i])

    urls = {}
    for i in stockset:
        urls[i.name] = i.get_absolute_url
  

    for i in range(0,len(set_name)):
        if fname[i] in urls.keys():
            print(urls[fname[i]])


    context = {
        "object_list":stockset,
        'new_dict':new_dict,
        'range':range(0,len(set_name)),
        'fname':fname,
        'fqty':fqty,
        'fbp':fbp,
        'fttl':fttl,
        'urls':urls
    }
    return render(request,"stocks/stock_list.html",context)


# def dynamic_lookup_view(request, my_id):
#     # obj = Product.objects.get(id=my_id)
#     obj = get_object_or_404(Stock, id=my_id)
#     # try:
#     #     obj = Product.objects.get(id=my_id)
#     # except Product.DoesNotExist:
#     #     raise Http404
#     context = {
#         "object":obj
#     }
#     return render(request,"stocks/stock_detail.html",context)



def single_stock_details(request, my_name):

    # stocks = get_object_or_404(Stock, name=my_name)
    single_stock = Stock.objects.filter(slug=my_name)
    first_stock_name = single_stock[0]
    print(single_stock[0].name)

    context = {
        # "object":stocks,
        "single_stock":single_stock,
        "first_stock_name":first_stock_name
    }
    return render(request,"stocks/stock_detail.html",context)


def dummy_func(request):
    stockset = Stock.objects.all()
    for i in stockset:
        if stockset.count(i.name)>1:
            print(i)
        else:
            print("Double")

    return render(request,"stocks/stock_list.html",{})






























































































# def stock_detail_view(request):
#     obj = Stock.objects.get(id=1)
#     # context = {
#     #     'title' : obj.title,
#     #     'description' : obj.description
#     # }
#     context = {
#         'object' : obj,
#         # 'value'  : obj.buy_price*obj.quantity
#     }
#     return render(request,"stocks/stock_detail.html",context)



# def with_pandas():
#     new_query = Stock.objects.all()
#     new_list = []
#     for i in new_query:
#         new_list.append(i.name)
#     data = {
#         'name': new_list
#     }
#     return render(request,"stocks/stock_detail.html",context)


# def render_initial_data(request):
#     initial_data = {
#         'title':"This is awesome"
#     }
#     obj = Stock.objects.get(id=10)
#     form = StockAddForm(request.POST or None, instance=obj)
#     if form.is_valid():
#         form.save()
#     context = {
#         'form':form
#     }
#     return render(request,"stocks/stock_create.html",context)




# def list_view_with_avg_bp(request):
#     name = []
#     qty = []
#     bp = []
#     ttl = []
#     for i in Stock.objects.all():
#         name.append(i.name)
#         qty.append(i.quantity)
#         bp.append(i.buy_price)
#         ttl.append(i.buy_price*i.quantity)
#     data = {
#         'name':name,
#         'qty':qty,
#         'bp':bp,
#         'ttl':ttl
#     }
#     df = pd.DataFrame(data=data)
#     sum_of_qty = df.groupby('name')['qty'].sum()
#     sum_bp = df.groupby('name')['ttl'].sum()
#     avg_bp = sum_bp/sum_of_qty
#     set_name = set(name)
#     new_dict = {}
#     for i in set_name:
#         new_dict[i] = avg_bp[i]
#     # print(new_dict)
#     # print(df)
#     # print(set_name)
#     # print(avg_bp)
#     context = {
#         "set_name":set_name,
#         "avg_bp":avg_bp,
#         'range':range(0,len(set_name)),
#         'new_dict':new_dict
#     }
#     return render(request,"stocks/portfolio.html",context)

Portfolio/dashboard/templates/stocks/portfolio.html
{% extends 'base.html' %}

{% block heading %} Portfolio {% endblock %}


{% block content %}

<p><a href="">Gold Holding</a> Need to add total equity holding</p>

<div class="row">
    <div class="col-md-4">
        <a class="dropdown-item" href="{% url 'portfolio:stock_list_view' %}">Equity Holding : {{ equity_sum }}</a> 
    </div>
    <div class="col-md-4 offset-md-4">
        <a class="btn btn-secondary btn-sm" tabindex="-1" role="button" aria-disabled="true" href="{% url 'portfolio:stock_create_view' %}">Add Stocks</a>
    </div>
</div>

{% endblock %}

Portfolio/dashboard/templates/stocks/stock_create.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="container">
      <div class="row">
        <div class="col-auto me-auto">
          <a class="btn btn-secondary btn-sm" tabindex="-1" role="button" aria-disabled="true" href="{% url 'dashboard:portfolio' %}">Portfolio</a>
        </div>
        <div class="col-auto">
          <a class="btn btn-secondary btn-sm" tabindex="-1" role="button" aria-disabled="true" href="{% url 'portfolio:stock_list_view' %}">Equity</a>
        </div>
      </div>
    </div>
</div>
<br>



<form action="." method="POST"> {% csrf_token %}

  {% for i in form %}
    <div class="row mb-3 justify-content-center">
      <label for="colFormLabel" class="col-sm-2 col-form-label">{{ i.label }}</label>
      <div class="col-sm-6">
        {{ i }}
        <datalist id="datalistOptions">
          {% for i in stock_names_list %}
            <option value="{{ i }}">
          {% endfor %}
        </datalist>    
      </div>
    </div>
  {% endfor %}


  <div class="container">
    <div class="row justify-content-center">
      <div class="col-4">
      <input class="btn btn-secondary btn-sm col-6" tabindex="-1" role="button" aria-disabled="true" type="submit" value="Add">
    </div>
    </div>
  </div>

</form>




{% endblock %}

Portfolio/dashboard/templates/stocks/stock_detail.html
{% extends 'base.html' %}

{% block heading %} 

{{ first_stock_name.name }} Details

{% endblock %}



{% block content %}

<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-auto me-auto">
        <a class="btn btn-secondary btn-sm" tabindex="-1" role="button" aria-disabled="true" href="{% url 'dashboard:portfolio' %}">Portfolio</a>
      </div>
      <div class="col-auto">
        <a class="btn btn-secondary btn-sm" tabindex="-1" role="button" aria-disabled="true" href="{% url 'portfolio:stock_list_view' %}">Equity</a>
      </div>
    </div>
  </div>
</div>

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Buying Price</th>
        <th scope="col">Avg Buying Price</th>
        <th scope="col">Buying Date</th>
        <th scope="col">Updated Date</th>
      </tr>
    </thead>
    <tbody>
      {% for i in single_stock %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ i.name }}</td>
        <td>{{ i.quantity }}</td>
        <td>{{ i.buy_price|floatformat:2 }}</td>
        <td>{% widthratio i.quantity 1 i.buy_price %}</td>
        <td>{{ i.buy_date }}</td>
        <td>{{ i.updated }}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>

{% endblock %}













<!-- <h1>In App template: {{ object.title }}</h1>
<p>{% if object.description != None and object.description != '' %}{{ object.description }}{% else %}Description is coming soon{% endif %}</p> -->

{% comment %} <h3>{{ object.name }}</h3>
<p>Quantity: {{ object.quantity }}</p>
<p>Average Buying Price: {{ object.buy_price }}</p>
<p>Invested Value: {% widthratio object.quantity 1 object.buy_price %}</p> {% endcomment %}


{% comment %} <h3>{{ object.name }}</h3>
<p>Quantity: {{ object.quantity }}</p> {% endcomment %}

{% comment %} {% for i in newli %}

<p>{{ i.name }} - {{ i.quantity }} - {{ i.buy_price }} - {% widthratio i.quantity 1 i.buy_price %} - {{ i.buy_date }}</p>

{% endfor %} {% endcomment %}

Portfolio/dashboard/templates/stocks/stock_list.html
{% extends 'base.html' %}

{% block heading %} Equity Holdings {% endblock %}


{% block content %}

<!-- {% for instance in object_list %}

    <p>{{ instance.id }} - <a href="{{ instance.get_absolute_url }}">{{ instance.name }} - {{ instance.quantity }} - {{ instance.buy_price }} - {{ instance.qty_price_mul }}</a></p>

{% endfor %} -->


{% load index %}


<div class="container">
  <div class="container">
    <div class="row">
      <div class="col-auto me-auto">
        <a class="btn btn-secondary btn-sm" tabindex="-1" role="button" aria-disabled="true" href="{% url 'dashboard:portfolio' %}">Portfolio</a>
      </div>
      <div class="col-auto">
        <a class="btn btn-secondary btn-sm" tabindex="-1" role="button" aria-disabled="true" href="{% url 'portfolio:stock_create_view' %}">Add Stocks</a>
      </div>
    </div>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Avg Buying Price</th>
      <th scope="col">Total Invested</th>
    </tr>
  </thead>
  <tbody>
    {% for i in range %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>
        {% for k, v in urls.items %}
          {% if fname|index:i == k %}
          <p><a class="dropdown-item" href="{{ v }}">{{ k }}</a></p>
          {% endif %}
        {% endfor %}
      </td>
      <td>{{ fqty|index:i }}</td>
      <td>{{ fbp|index:i|floatformat:2 }}</td>
      <td>{{ fttl|index:i|floatformat:2 }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>





{% endblock %}



{% comment %}


<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Avg Buying Price</th>
      <th scope="col">Total Invested</th>
    </tr>
  </thead>
  <tbody>
    {% for i in range %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ fname|index:i }}</td>
      <td>{{ fqty|index:i }}</td>
      <td>{{ fbp|index:i|floatformat:2 }}</td>
      <td>{{ fttl|index:i|floatformat:2 }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table> 



{% for i in range %}
  {% if fname|index:i in urls.keys %}
    <p><a href="{{ urls.values }}">{{ fname|index:i }}</a></p>
  {% endif %}
{% endfor %}


{% for i, j in urls.items %}
<p><a href="{{ j }}">{{ i }}</a></p>
{% endfor %}

{% for i in urls %}
<p>{{ i }}</p>
{% endfor %}



{% endcomment %}